    - include_tasks: Usersandwhitelist.yml
      when: AddUsersandwhitelist == "true"
   
    - name: Install required packages for Duo MFA
      yum:
        name:
          - openssl-devel
          - pam-devel
          - gcc
        state: present

    - name: Download Duo  MFA
      get_url:
        url: https://dl.duosecurity.com/duo_unix-latest.tar.gz
        dest: /root/

    - name: Find the Duo tarball
      shell: ls /root/ | grep 'duo_unix' | grep gz
      register: duotarball

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: duotarball

    - name: Uncompress Duo MFA Tarball
      unarchive:
        remote_src: yes
        src: "/root/{{ duotarball.stdout }}"
        dest: /root/

    - name: Pull duo directory name
      shell: ls /root/ | grep duo_unix | grep -v gz
      register: duodirectory

    - name: cd to /root/duo_unix-1.12.0 and install MFA
      shell: cd /root/{{ duodirectory.stdout }}; ./configure --with-pam --prefix=/usr; make && make install


    - name: Add the ikey address to Duo config.
      lineinfile:
        path: '{{ duopampath }}'
        regex: '^ikey ='
        line: "ikey = {{ ikeyaddress }}"

    - name: Add the skey address to Duo config.
      lineinfile:
        path: '{{ duopampath }}'
        regex: '^skey ='
        line: "skey = {{ skeyaddress }}"



    - name: Add the host address to Duo config.
      lineinfile:
        path: '{{ duopampath }}'
        regex: '^host ='
        line: "host = {{ hostaddress }}"


    - name: Add the groups to whitelist to Duo config.
      lineinfile:
        path: '{{ duopampath }}'
        regex: '^groups ='
        line: "groups = {{ wlgroups }}"


    - name: Add the groups to whitelist to Duo config.
      lineinfile:
        path: '{{ duopampath }}'
        regex: '^gecos_delim='
        line: 'gecos_delim=/'



    - name: Add the groups to whitelist to Duo config.
      lineinfile:
        path: '{{ duopampath }}'
        regex: '^gecos_username_pos'
        line: 'gecos_username_pos=6'


    - include_tasks: PassandPubkeyDuo.yml
      when: DuoSetupMethod == "PassAndPubkey"

    - include_tasks: PubkeyDuo.yml
      when: DuoSetupMethod == "Pubkey"

    - include_tasks: Restartsshd.yml
      when: restartsshd == true

